name: 'Home Assistant helper: version-push'
description: 'GitHub action helper: version-push'
inputs:
  key:
    required: true
    default: ''
    description: "JSON key to replace version with, e.g. supervisor, homeassistant.default or hassos[] to replace for all properties in hassos."
  key-description:
    required: false
    default: {{ inputs.key }}
    description: "Human Friendly description of key which is beeing changed for git commit message."
  version:
    required: true
    default: ''
  channel:
    default: 'dev'
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        if [[ -z "${{ inputs.key }}" ]];then
          echo "::error::Missing required key 'key' input!"
          exit 1
        elif [[ -z "${{ inputs.version }}" ]];then
          echo "::error::Missing required key 'version' input!"
          exit 1
        fi

    - shell: bash
      run: git clone --depth 1 https://github.com/agners/version.git /tmp/version

    - shell: bash
      run: |
        temp=$(mktemp)
        jq '.${{ inputs.key }} |= "${{ inputs.version }}"' "/tmp/version/${{ inputs.channel }}.json" > "${temp}"
        mv "${temp}" "/tmp/version/${{ inputs.channel }}.json"

    - shell: bash
      run: |
        cd /tmp/version
        git commit -am "Bump ${{ inputs.key-description }} to ${{ inputs.version }}"
        git push
        rm -r /tmp/version
